spring:
  application:
    name: nacos-loadbalancer-demo
  profiles:
    active: @spring.profiles.active@

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always