spring:
  application:
    name: nacos-discovery-demo
  profiles:
    active: @spring.profiles.active@

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always